
services:
  backend-test:
    build: ./api_test
    ports:
      - "3333:3333"
    volumes:
      - ./api_test/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3333

  postgres:
      image: postgres:14-alpine
      restart: always
      env_file:
        - ./api_test/.env
      ports:
        - "5432:5432"
      volumes:
        - ./db:/var/lib/postgresql/data